---
title: Invoice Lifecycle — Zapier
---
flowchart TD
    T["Receive Event"]:::trigger
    A1["Get Cursor"]
    A2["List Project Types"]
    A3["Map Project Types"]
    A4["Fetch QBO Invoices"]
    A5["Get Job"]
    A6["Get Preferences"]
    A7["Get Invoice"]
    A8["Get Customer By Id"]
    A9["(Job) Customer\nPayload"]
    A10["Update Parent\nCustomer"]
    A11["List Invoices Linked\nto Job"]
    A12["Invoice Lines IDs\nstring"]
    A13["Get Invoice Lines"]
    A14["Create Lines Array"]
    A15["Fill Custom Fields"]
    A16["Create Invoice\nPayload"]
    A17["Create Invoice"]
    A18["Initial Status"]
    A19["Get All Invoices"]
    A20["Filter Voided\nInvoices"]
    A21["Send Invoice"]
    A22["Find Associated Job"]
    A23["Bill to String"]
    A24["Invoice Payload"]
    A25["Upsert Invoice"]
    A26["Process Invoice Line\nItems"]
    A27["Crossflow Payload"]
    A28["Process Payments"]
    A29["PDF Subflow Payload"]
    A30["Save Invoice PDF"]
    A31["Filter Transactions"]
    A32["Get All Payment\nMethods"]
    A33["Loop Over Payments"]
    A34["Get Invoice By Id"]
    A35["Update Invoice\nPayload"]
    A36["Update Invoice"]
    A37["Update Doc Number\nPayload"]
    A38["Update Doc Number"]
    A39["Void Invoice"]
    A40["Records to be\nprocessed?"]
    A41["Job Found?"]
    A42["Invoice created\nsuccessfully?"]
    A43["Got any invocies\nfrom QBO?"]
    A44["Status Branch"]
    A45["Branch on Expression"]
    A46["Update Successful?"]

    T --> A1 --> A2 --> A3 --> A4 --> A5 --> A6 --> A7 --> A8 --> A9 --> A10 --> A11 --> A12 --> A13 --> A14 --> A15 --> A16 --> A17 --> A18 --> A19 --> A20 --> A21 --> A22 --> A23 --> A24 --> A25 --> A26 --> A27 --> A28 --> A29 --> A30 --> A31 --> A32 --> A33 --> A34 --> A35 --> A36 --> A37 --> A38 --> A39 --> A40 --> A41 --> A42 --> A43 --> A44 --> A45 --> A46

    classDef trigger fill:#FF4A00,stroke:#cc3b00,stroke-width:3px,color:#fff
