---
title: Invoice Lifecycle — Zapier
---
flowchart TD
    T["Receive Event"]:::trigger
    A1["Get Cursor"]
    A2["List Project Types"]
    A3["Map Project Types"]
    A4["Fetch QBO Invoices"]
    A5["Get Accepted Quotes"]
    A6["Loop Over Items"]
    A7["Stop Execution 2"]
    A8["Estimate Date To\nSync"]
    A9["Time 2 Minutes Ago"]
    A10["Time 2 Minutes Ago\nto Epoch"]
    A11["Code Block"]
    A12["List Quotes"]
    A13["Loop Over Quotes"]
    A14["Get Job"]
    A15["Get Preferences"]
    A16["Get Invoice"]
    A17["Get Customer By Id"]
    A18["(Job) Customer\nPayload"]
    A19["Update Parent\nCustomer"]
    A20["List Invoices Linked\nto Job"]
    A21["Invoice Lines IDs\nstring"]
    A22["Get Invoice Lines"]
    A23["Create Lines Array"]
    A24["Fill Custom Fields"]
    A25["Create Invoice\nPayload"]
    A26["Create Invoice"]
    A27["Initial Status"]
    A28["Get All Invoices"]
    A29["Filter Voided\nInvoices"]
    A30["Send Invoice"]
    A31["Find Associated Job"]
    A32["Bill to String"]
    A33["Invoice Payload"]
    A34["Upsert Invoice"]
    A35["Process Invoice Line\nItems"]
    A36["Crossflow Payload"]
    A37["Process Payments"]
    A38["PDF Subflow Payload"]
    A39["Save Invoice PDF"]
    A40["Filter Transactions"]
    A41["Get All Payment\nMethods"]
    A42["Loop Over Payments"]
    A43["Get Invoice By Id"]
    A44["Update Invoice\nPayload"]
    A45["Update Invoice"]
    A46["Update Doc Number\nPayload"]
    A47["Update Doc Number"]
    A48["Void Invoice"]
    A49["Records to be\nprocessed?"]
    A50["Job Found?"]
    A51["Invoice created\nsuccessfully?"]
    A52["Got any invocies\nfrom QBO?"]
    A53["Status Branch"]
    A54["Branch on Expression"]
    A55["Update Successful?"]

    T --> A1 --> A2 --> A3 --> A4 --> A5 --> A6 --> A7 --> A8 --> A9 --> A10 --> A11 --> A12 --> A13 --> A14 --> A15 --> A16 --> A17 --> A18 --> A19 --> A20 --> A21 --> A22 --> A23 --> A24 --> A25 --> A26 --> A27 --> A28 --> A29 --> A30 --> A31 --> A32 --> A33 --> A34 --> A35 --> A36 --> A37 --> A38 --> A39 --> A40 --> A41 --> A42 --> A43 --> A44 --> A45 --> A46 --> A47 --> A48 --> A49 --> A50 --> A51 --> A52 --> A53 --> A54 --> A55

    classDef trigger fill:#FF4A00,stroke:#cc3b00,stroke-width:3px,color:#fff
